

import streamlit as st
from datetime import date
import io
import uuid

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from theme import inject_theme, top_nav, page_header, risk_badge, footnote, panel

st.set_page_config(
    page_title="Reports • CuraVision AI",
    page_icon="🩺",
    layout="wide",
    initial_sidebar_state="collapsed",
)

if not st.session_state.get("logged_in"):
    st.switch_page("pages/login.py")

REPORTS_CSS = """
div[class*="st-key-reportrow_"] {
    background: var(--surface);
    border: 1px solid var(--line);
    border-radius: var(--radius-sm);
    padding: 14px 18px 2px 18px;
    margin-bottom: 10px;
}
"""

inject_theme(REPORTS_CSS)
top_nav()

page_header(
    "Medical reports",
    "Review past detection results, drill into details, or export any report as a PDF.",
    "file",
)

# --- mock / session data — replace with your DB or storage-backed fetch ---
if "reports" not in st.session_state:
    st.session_state.reports = [
        {
            "id": str(uuid.uuid4())[:8],
            "date": date(2026, 8, 4),
            "type": "Combined (Image + Symptoms)",
            "risk": "high",
            "confidence": 72.3,
            "summary": "Chest X-ray flagged density irregularity; symptoms included fever and shortness of breath.",
            "patient": "You",
        },
        {
            "id": str(uuid.uuid4())[:8],
            "date": date(2026, 7, 28),
            "type": "Symptom Checker",
            "risk": "low",
            "confidence": 18.5,
            "summary": "Mild headache and fatigue, short duration, low overall severity.",
            "patient": "You",
        },
        {
            "id": str(uuid.uuid4())[:8],
            "date": date(2026, 7, 15),
            "type": "Image Detection",
            "risk": "low",
            "confidence": 22.0,
            "summary": "Skin lesion photo analyzed, no abnormality detected.",
            "patient": "You",
        },
    ]


# --- PDF generation ---
# cached so a rerun (filter change, expander click, etc.) doesn't rebuild
# every visible report's PDF from scratch each time
@st.cache_data
def build_report_pdf(report: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=2 * cm, bottomMargin=2 * cm,
        leftMargin=2 * cm, rightMargin=2 * cm,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleTeal", parent=styles["Title"], textColor=colors.HexColor("#1F4E42"),
        fontName="Helvetica-Bold",
    )
    heading_style = ParagraphStyle(
        "HeadingTeal", parent=styles["Heading2"], textColor=colors.HexColor("#2F6F5E"),
    )
    body_style = styles["BodyText"]

    elements = []
    elements.append(Paragraph("CuraVision AI — Medical Report", title_style))
    elements.append(Spacer(1, 0.4 * cm))
    elements.append(Paragraph(f"Report ID: {report['id']}", body_style))
    elements.append(Paragraph(f"Date: {report['date'].strftime('%B %d, %Y')}", body_style))
    elements.append(Paragraph(f"Patient: {report['patient']}", body_style))
    elements.append(Spacer(1, 0.6 * cm))

    elements.append(Paragraph("Assessment Details", heading_style))
    table_data = [
        ["Detection Type", report["type"]],
        ["Risk Level", report["risk"].upper()],
        ["Confidence Score", f"{report['confidence']}%"],
    ]
    table = Table(table_data, colWidths=[6 * cm, 9 * cm])
    table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#B9BFAE")),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#E1EBE4")),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 0.6 * cm))

    elements.append(Paragraph("Summary", heading_style))
    elements.append(Paragraph(report["summary"], body_style))
    elements.append(Spacer(1, 0.8 * cm))

    disclaimer = (
        "Disclaimer: This report was generated by an AI-assisted preliminary screening "
        "tool and does not constitute a medical diagnosis. Please consult a licensed "
        "healthcare professional for confirmation, further testing, and treatment."
    )
    elements.append(Paragraph(disclaimer, ParagraphStyle(
        "Disclaimer", parent=body_style, textColor=colors.HexColor("#57635C"), fontSize=8.5
    )))

    doc.build(elements)
    buffer.seek(0)
    return buffer.read()


# --- filter bar ---
with panel("flat"):
    f1, f2, f3 = st.columns([2, 2, 2])
    with f1:
        type_filter = st.multiselect(
            "Detection type",
            ["Image Detection", "Symptom Checker", "Combined (Image + Symptoms)"],
            default=[],
            placeholder="All types",
        )
    with f2:
        risk_filter = st.multiselect(
            "Risk level", ["high", "low"], default=[], placeholder="All risk levels"
        )
    with f3:
        sort_order = st.selectbox("Sort by", ["Newest first", "Oldest first"])

# --- apply filters ---
reports = st.session_state.reports.copy()
if type_filter:
    reports = [r for r in reports if r["type"] in type_filter]
if risk_filter:
    reports = [r for r in reports if r["risk"] in risk_filter]
reports.sort(key=lambda r: r["date"], reverse=(sort_order == "Newest first"))

# --- report list ---
if not reports:
    st.info("No reports match the selected filters.")
else:
    for report in reports:
        with st.container(key=f"reportrow_{report['id']}"):
            c1, c2, c3, c4, c5 = st.columns([2, 3, 2, 2, 2])

            with c1:
                st.markdown(f"**{report['date'].strftime('%b %d, %Y')}**")
                st.caption(f"ID: {report['id']}")
            with c2:
                st.write(report["type"])
            with c3:
                st.markdown(risk_badge(report["risk"]), unsafe_allow_html=True)
            with c4:
                st.write(f"{report['confidence']}%")
            with c5:
                pdf_bytes = build_report_pdf(report)
                st.download_button(
                    "Download PDF",
                    data=pdf_bytes,
                    file_name=f"curavision_report_{report['id']}.pdf",
                    mime="application/pdf",
                    key=f"dl_{report['id']}",
                )

            with st.expander("View full summary"):
                st.write(report["summary"])
                st.caption("This report was generated by CuraVision AI's detection models.")

footnote(
    "All reports on this page are AI-generated preliminary assessments, not medical "
    "diagnoses. Always consult a licensed healthcare professional."
)
